# Generated by Django 6.0.4 on 2026-05-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_columnmetadata_suggested_name_dataset_row_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='columnmetadata',
            name='advanced_stats',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
