import pandas as pd
from rest_framework import viewsets, status
from rest_framework.response import Response
from rest_framework.decorators import action
from .models import Dataset, ColumnMetadata
from .serializers import DatasetSerializer, ColumnMetadataSerializer

class DatasetViewSet(viewsets.ModelViewSet):
    queryset = Dataset.objects.all().order_by('-uploaded_at')
    serializer_class = DatasetSerializer

    def create(self, request, *args, **kwargs):
        file_obj = request.data.get('file')
        if not file_obj:
            return Response({'error': 'No file provided'}, status=status.HTTP_400_BAD_REQUEST)
        
        dataset = Dataset.objects.create(name=file_obj.name, file=file_obj)
        
        # Process with pandas
        try:
            if file_obj.name.endswith('.csv'):
                df = pd.read_csv(dataset.file.path)
            elif file_obj.name.endswith('.xlsx'):
                df = pd.read_excel(dataset.file.path)
            elif file_obj.name.endswith('.json'):
                df = pd.read_json(dataset.file.path)
            else:
                return Response({'error': 'Unsupported file format'}, status=status.HTTP_400_BAD_REQUEST)

            # Generate Dataset Metadata
            total_rows = len(df)
            health_score = 100
            
            # Simple metadata extraction
            for col in df.columns:
                null_count = int(df[col].isnull().sum())
                unique_count = int(df[col].nunique())
                data_type = str(df[col].dtype)
                
                # Mock AI Description
                ai_desc = f"AI description for {col}."
                if 'id' in col.lower():
                    ai_desc = f"Unique identifier for {col.replace('_id', '')}."
                elif 'date' in col.lower() or 'dob' in col.lower():
                    ai_desc = f"Date field representing {col}."

                # Get sample values (non-null)
                sample_vals = df[col].dropna().unique()[:3].tolist()
                
                if null_count > 0:
                    health_score -= (null_count / total_rows) * 10 # simple penalty
                
                ColumnMetadata.objects.create(
                    dataset=dataset,
                    name=col,
                    data_type=data_type,
                    ai_description=ai_desc,
                    null_count=null_count,
                    unique_count=unique_count,
                    sample_values=sample_vals
                )
            
            dataset.health_score = max(0, min(100, int(health_score)))
            dataset.summary = f"This dataset contains {total_rows} rows and {len(df.columns)} columns. Generated by AI."
            dataset.status = 'completed'
            dataset.save()
            
            serializer = self.get_serializer(dataset)
            return Response(serializer.data, status=status.HTTP_201_CREATED)

        except Exception as e:
            dataset.status = 'failed'
            dataset.save()
            return Response({'error': str(e)}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)

    @action(detail=True, methods=['post'])
    def query(self, request, pk=None):
        dataset = self.get_object()
        query = request.data.get('query', '').lower()
        
        # Mock NLP logic for answering questions
        columns = dataset.columns.all()
        response_text = "I couldn't understand your question."
        
        if 'what does' in query and 'mean' in query:
            # "what does customer_id mean?"
            for col in columns:
                if col.name in query:
                    response_text = f"{col.name} means: {col.ai_description}"
                    break
        elif 'show all' in query and 'columns' in query:
            response_text = "Here are the columns: " + ", ".join([c.name for c in columns])
        
        return Response({'answer': response_text})
